// Common
export const SHOW_LOADING = 'SHOW_LOADING';
export const SHOW_CONFIRM_DIALOG = 'SHOW_CONFIRM_DIALOG';
export const SHOW_ALERT_DIALOG = 'SHOW_ALERT_DIALOG';
export const LOGOUT = 'LOGOUT';
export const CHANGE_ROOT_SCREEN = 'CHANGE_ROOT_SCREEN';

// Login
export const LOGIN = 'LOGIN';

// Chat
export const GET_LIST_FRIENDS = 'GET_LIST_FRIENDS';
export const GET_LIST_FRIENDS_SUCCESS = 'GET_LIST_FRIENDS_SUCCESS';
export const GET_MESSAGES = 'GET_MESSAGES';
export const GET_MESSAGES_SUCCESS = 'GET_MESSAGES_SUCCESS';

// Friends
export const SEARCH_FRIENDS = 'SEARCH_FRIENDS';
export const GET_FRIENDS_SUCCESS = 'GET_FRIENDS_SUCCESS';
export const CLEAR_SEARCH_FRIENDS = 'CLEAR_SEARCH_FRIENDS';
export const ADD_FRIEND = 'ADD_FRIEND';
export const REMOVE_FRIEND_ADD_SUCCESS = 'REMOVE_FRIEND_ADD_SUCCESS';
export const GET_LIST_FRIENDS_ADDED = 'GET_LIST_FRIENDS_ADDED';
export const GET_LIST_FRIENDS_ADDED_SUCCESS = 'GET_LIST_FRIENDS_ADDED_SUCCESS';
export const ACCEPT_FRIEND = 'ACCEPT_FRIEND';
export const ACCEPT_FRIEND_SUCCESS = 'ACCEPT_FRIEND_SUCCESS';

// Params Scene
export const UPDATE_PARAMS_CHAT_SCENE = 'UPDATE_PARAMS_CHAT_SCENE';