# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Trust' do
  
  pod 'AgoraRtcEngine_iOS'

  # Required by RNFirebase
  pod 'Firebase/Core', '~> 5.15.0'
  pod 'Firebase/Auth'

end