# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Trust' do
  
  # pod 'AgoraRtcEngine_iOS'

  # Required by RNFirebase
  pod 'Firebase/Core', '~> 5.15.0'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'

  # pod 'react-native-agora', :path => '../node_modules/react-native-agora'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|

    # The following is needed to ensure the "archive" step works in XCode.
    # It removes React & Yoga from the Pods project, as it is already included in the main project.
    # Without this, you'd see errors when you archive like:
    # "Multiple commands produce ... libReact.a"
    # "Multiple commands produce ... libyoga.a"

    targets_to_ignore = %w(React yoga)
    
    if targets_to_ignore.include? target.name
      target.remove_from_project
    end

  end
end